### ISSUE TITLE
problem: 使用的问题

### ISSUE THREAD

**Issue by Fanzi00** [bismarckkk/RM-UI-Designer#49]
问几个使用过程中的问题：
1.我在使用这个生成的代码时，是不是只要调用带有init的初始化函数就可以了(当然是加了串口的)？
2.在修改图形时，是不是要对带有updata的函数修改？
![updata](https://github.com/bismarckkk/RM-UI-Designer/assets/140720456/9d8989c3-4e68-472f-b8fb-bfa4012919f4)

![init](https://github.com/bismarckkk/RM-UI-Designer/assets/140720456/37a088c5-98e6-41b4-a61a-f5da3462ace6)

**Comment by bismarckkk** [comment]
你好，
这个部分生成的代码一般不需要修改，除非只是修改了元素的初始状态，并且懒得用设计器重新生成代码
如果在车上使用的话一般是按下一个键就调用一次init函数，方便操作手手动刷新ui，调试的话可以上电以后就调用init函数（可能需要多调用几次，裁判系统经常丢包）
update函数一般放在一个rtos的线程里循环调用即可（建议把动态和静态元素分在不同的group里，会生成不同的update函数，只需要调用动态元素的update函数即可），代码中将每个元素都导出了一个单独的对应类型的指针，只需要在需要修改的地方直接修改该指针指向结构体的内容。每次调用update函数时会自动获取最新的数据并发送
另外这些_ui开头的函数都是split内部的函数，在ui.h中为每个group提供了一个对外的接口，避免对同一个group编写多余代码
详细的可以参考serial_test/main.cpp中的示例，该文件夹中提供了一个简易的生成代码的使用范例（用于在pc上使用，为了调用串口库使用了cpp编程，实际逻辑无影响）
